[[main]]
  name = "☯︎\u00A0Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "☯︎\u00A0About"
  pageRef = "o-mne"
  weight = 10

[[main]]
  name = "☯︎\u00A0Logo"
  pageRef = "/logo"
  weight = 20

[[main]]
  name = "☯︎\u00A0Contests"
  pageRef = "souteze"
  weight = 30

[[main]]
  name = "☯︎\u00A0Photo"
  pageRef = "foto"
  weight = 40

[[main]]
  name = "☯︎\u00A0Videos"
  pageRef = "/videa"
  weight = 50

[[main]]
  name = "☯︎\u00A0Contact"
  pageRef = "kontakt"
  weight = 60