[[main]]
  name = "☯︎\u00A0홈"
  pageRef = "/"
  weight = 1

[[main]]
  name = "☯︎\u00A0나에 대해"
  pageRef = "/o-mne"
  weight = 10

[[main]]
  name = "☯︎\u00A0로고"
  pageRef = "/logo"
  weight = 20

[[main]]
  name = "☯︎\u00A0대회"
  pageRef = "/souteze"
  weight = 30

[[main]]
  name = "☯︎\u00A0사진"
  pageRef = "/foto"
  weight = 40

[[main]]
  name = "☯︎\u00A0비디오"
  pageRef = "/videa"
  weight = 50

[[main]]
  name = "☯︎\u00A0연락하기"
  pageRef = "/kontakt"
  weight = 60