[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "o-mne"
  weight = 20

[[main]]
  name = "Contests"
  pageRef = "souteze"
  weight = 30

[[main]]
  name = "Photo"
  pageRef = "foto"
  weight = 40


[[main]]
  name = "Contact"
  pageRef = "kontakt"
  weight = 50