[author]
  name = ""
  image = "banner01.jpg"   # Tady musí být ta fotka pro profil!
 

# Tady začínají parametry šablony
[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  enableSearch = false
  disableTextInHeader = true

[header]
  layout = "basic"
  logoType = "image"
  showTitle = false
  showLogo = true
  disableTextInHeader = true

[homepage]
  layout = "profile"
  showAvatar = true
  avatar = "banner01.jpg" # Ujisti se, že je v assets nebo static
  avatarSize = "20rem"    # Tady si pak můžeš nastavit velikost
  homepageImage = ""
  showHero = true
  showRecent = false
  showLinks = true  # <--- TOTO PŘIDEJ, aby se zobrazila ikona Instagramu
  align = "left"
  heroSubtitle = "Tuto stránku jsem vytvořil jako místo, kde můžu sdílet svou cestu, chyby i úspěchy. Jsem rád, že jsi tady. <br>Pokud chceš vidět více z mých tanečních coverů a jiných akcí, mrkni na Instagram. <br><br><div style='text-align: center; margin-top: 25px;'><img src='/images/liska2.webp' alt='Liška' style='width: 140px; height: auto; display: inline-block; border-radius: 12px; filter: drop-shadow(0 5px 15px rgba(0,0,0,0.4));'></div>"

[params.assets]
  customCSS = ["css/custom.css"]

[article]
  showDate = false
  showViews = false
  showLikes = false
  showAuthor = false
  showAuthorBottom = false
  showHero = false
  showBreadcrumbs = false
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false